10_12

diff --git a/.github/workflows/ci_cd_python.yml b/.github/workflows/ci_cd_python.yml
--- a/.github/workflows/ci_cd_python.yml
+++ b/.github/workflows/ci_cd_python.yml
@@ -40,6 +40,12 @@ jobs:
       - name: Lint with pylint
         run: pylint **/*.py  # Lint all Python files in the repository
 
+      - name: Check for "uld_raw" in script.py
+        run: |
+          if grep -q "uld_raw" script.py; then
+            echo "Error: 'uld_raw' found in script.py"
+            exit 1  # This will fail the job if "uld_raw" is found
+          fi
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
